title: Impactful words by Dr.Jordan B. peterson
author: Dico-Akidiva
email: dicoakidiva@gmail.com
description: >
In his book, 12 rules fo life, Jordan Peterson talks about how the ideal life should be lived.
It is an international best seller and the book has transformed peoples lives tremendously.
His lectures aswell on youtube have over a million views.

twitter_username: dicoakidiva
github_username: Dico-Akidiva

show_excerpts: false
