title: Impactful Words by Dr.Jordan B. Peterson
author: Dico-Akidiva
email: dicoakidiva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In his book, 12 rules of life, Jordan Peterson talks about how the ideal life should be lived. 
  It's an international best seller and the book has transformed people lives tremendously. 
  His lectures aswell on youtube have one million views. 
  Here are some of his words that some may relate.

# social links
twitter_username: dicoakidiva # DO NOT include the @ character, or else the build will fail!
github_username:  Dico-Akidiva # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
